[package]
name = "zcore_test"
version = "0.1.0"
authors = ["lincyaw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.5"
downcast-rs = { version = "1.2.0", default-features = false}